In [46]:
import tensorflow as tf
import numpy as np
#case 2
input = tf.constant(list(range(16)),shape=(1,2,2,4),dtype=tf.float32)
filter = tf.constant(list(range(8)),shape=(1,1,4,2),dtype=tf.float32)
op2 = tf.nn.conv2d(input, filter, strides=[1, 1, 1, 1], padding='VALID')
with tf.Session() as sess:
    print(sess.run(op2))
    print(sess.run(input))
    print(sess.run(input).flatten())
    print(sess.run(filter))

[[[[  28.   34.]
   [  76.   98.]]

  [[ 124.  162.]
   [ 172.  226.]]]]
[[[[  0.   1.   2.   3.]
   [  4.   5.   6.   7.]]

  [[  8.   9.  10.  11.]
   [ 12.  13.  14.  15.]]]]
[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.
  15.]
[[[[ 0.  1.]
   [ 2.  3.]
   [ 4.  5.]
   [ 6.  7.]]]]


In [31]:
np.arange(0,12).reshape((1,3,2,2))

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]]])

In [37]:
np.random.randint(0,100,[2,2])

array([[62, 42],
       [18, 10]])

In [50]:
a = np.ndarray(shape=(2,2), dtype=float,buffer=np.array([1,2,3,4]),order='C')

array([[  4.94065646e-324,   9.88131292e-324],
       [  1.48219694e-323,   1.97626258e-323]])

In [56]:
a = np.array(range(12)).reshape(2, 2, 3)  
print(a)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [61]:
print(a.reshape(3,2,2))

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [63]:
print (a.transpose(2,0,1))

[[[ 0  3]
  [ 6  9]]

 [[ 1  4]
  [ 7 10]]

 [[ 2  5]
  [ 8 11]]]
